name: materials_chempy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.6
  - pip
  - pandas
  - numpy
  - matplotlib

  - pip:
    - pyopenms
    - spectrum_overload
    - metapub
    - qiskit_sphinx_theme
    - sphinx-reredirects
    - sphinx-reredirects
    - pybliometrics
    - pygments-pytest

  # Test dependencies
  - pytest
  - coverage
  - flake8
  - unidecode
  - coloredlogs

  # Mass spectrometry dependencies

  # Spectrophotometry dependencies
  - astropy
  - specutils
  - scipy

  # Database analysis dependencies
  - lxml
  - pytrends

  # Chromatography dependencies
  - astropy
  - specutils
  - distinctipy

  # Documentation dependencies
  - sphinx
  - reno
  - nbsphinx
  - sphinx-remove-toctrees
  - sphinx-copybutton
  - numpydoc
  - sphinx-design
  - sphinx-autodoc-typehints
  - sphinx-togglebutton
  - docutils
