name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.6
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.6'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: environment variables config
      env:
        Elsevier_API: ${{ SCOPUS_API_KEY }}
      run: |
        touch ~/.config/pybliometrics.cfg
        echo '[Authentication]' >> ~/.config/pybliometrics.cfg
        echo "$Elsevier_API" >> ~/.config/pybliometrics.cfg
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=dev,notebooks
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=dev,notebooks
    - name: Test with pytest
      run: |
        cd ./docs
        make test
        # python -m pytest --doctest-modules -v --ignore=dev,notebooks --maxfail=4 ./docs .
